// Lista completa de módulos del ERP. Único uso hoy: rol SOPORTE recibe acceso a todos
// (auth.service.ts, getModulosActivos()). Separado de modules-by-plan.config.ts (Sistema 1,
// retirado en Fase 4) porque este archivo sí sigue siendo una fuente de verdad real.
export const ALL_MODULES = [
  'dashboard',
  'empresas',
  'sucursales',
  'usuarios',
  'configuracion',
  'bancos',
  'movimientos',
  'transferencias',
  'reportes',
  'tesoreria',
  'conciliacion',
  'pos',
  'pos_sin_inventario',
  'configuracion_pos',
  'corte_caja_lite',
  'apariencia_logo_only',
  'integraciones',
  'rh',
  'sat_cfdi',
  'white_label',
  'proveedores',
  'compras',
  'costos',
  'ocr',
  'audit',
];
