export enum Plan {
  LITE = 'LITE',
  BASIC = 'BASIC',
  PRO = 'PRO',
  BUSINESS = 'BUSINESS',
  ENTERPRISE = 'ENTERPRISE',
}

export const MODULES_BY_PLAN: Record<Plan, string[]> = {
  [Plan.LITE]: [
    'pos',
    'configuracion-pos',
  ],
  [Plan.BASIC]: [
    'dashboard',
    'empresas',
    'sucursales',
    'usuarios',
    'configuracion',
    'bancos',
    'movimientos',
    'transferencias',
  ],
  [Plan.PRO]: [
    'dashboard',
    'empresas',
    'sucursales',
    'usuarios',
    'configuracion',
    'bancos',
    'movimientos',
    'transferencias',
    'reportes',
    'tesoreria',
    'conciliacion',
    'proveedores',
    'compras',
  ],
  [Plan.BUSINESS]: [
    'dashboard',
    'empresas',
    'sucursales',
    'usuarios',
    'configuracion',
    'bancos',
    'movimientos',
    'transferencias',
    'reportes',
    'tesoreria',
    'conciliacion',
    'pos',
    'configuracion-pos',
    'integraciones',
    'proveedores',
    'compras',
    'costos',
  ],
  [Plan.ENTERPRISE]: [
    'dashboard',
    'empresas',
    'sucursales',
    'usuarios',
    'configuracion',
    'bancos',
    'movimientos',
    'transferencias',
    'reportes',
    'tesoreria',
    'conciliacion',
    'pos',
    'configuracion-pos',
    'integraciones',
    'rh',
    'sat-cfdi',
    'white-label',
    'proveedores',
    'compras',
    'costos',
    'ocr',
    'audit',
  ],
};

export function getModulesByPlan(plan: Plan): string[] {
  return MODULES_BY_PLAN[plan] || [];
}

// Todos los módulos disponibles para rol SOPORTE
export const ALL_MODULES = [
  'dashboard',
  'empresas',
  'sucursales',
  'usuarios',
  'configuracion',
  'bancos',
  'movimientos',
  'transferencias',
  'reportes',
  'tesoreria',
  'conciliacion',
  'pos',
  'configuracion-pos',
  'integraciones',
  'rh',
  'sat-cfdi',
  'white-label',
  'proveedores',
  'compras',
  'costos',
  'ocr',
  'audit',
];
