export enum Plan {
  LITE_CORTE = 'LITE_CORTE',
  LITE_POS   = 'LITE_POS',
  BASIC      = 'BASIC',
  PRO        = 'PRO',
  BUSINESS   = 'BUSINESS',
  ENTERPRISE = 'ENTERPRISE',
}

export const MODULES_BY_PLAN: Record<Plan, string[]> = {
  [Plan.LITE_CORTE]: [
    'dashboard',
    'corte_caja_lite',
    'pos',
    'usuarios',
    'empresas',
    'sucursales',
    'apariencia_logo_only',
  ],
  [Plan.LITE_POS]: [
    'dashboard',
    'pos_sin_inventario',
    'usuarios',
    'empresas',
    'sucursales',
    'apariencia_logo_only',
  ],
  [Plan.BASIC]: [
    'dashboard',
    'empresas',
    'sucursales',
    'usuarios',
    'configuracion',
    'bancos',
    'movimientos',
    'transferencias',
    'pacientes',
  ],
  [Plan.PRO]: [
    'dashboard',
    'empresas',
    'sucursales',
    'usuarios',
    'configuracion',
    'bancos',
    'movimientos',
    'transferencias',
    'reportes',
    'tesoreria',
    'conciliacion',
    'proveedores',
    'compras',
  ],
  [Plan.BUSINESS]: [
    'dashboard',
    'empresas',
    'sucursales',
    'usuarios',
    'configuracion',
    'bancos',
    'movimientos',
    'transferencias',
    'reportes',
    'tesoreria',
    'conciliacion',
    'pos',
    'configuracion_pos',
    'integraciones',
    'proveedores',
    'compras',
    'costos',
    'pacientes',
  ],
  [Plan.ENTERPRISE]: [
    'dashboard',
    'empresas',
    'sucursales',
    'usuarios',
    'configuracion',
    'bancos',
    'movimientos',
    'transferencias',
    'reportes',
    'tesoreria',
    'conciliacion',
    'pos',
    'configuracion_pos',
    'integraciones',
    'rh',
    'sat_cfdi',
    'white_label',
    'proveedores',
    'compras',
    'costos',
    'ocr',
    'audit',
  ],
};

export function getModulesByPlan(plan: Plan): string[] {
  return MODULES_BY_PLAN[plan] || [];
}

// Todos los módulos disponibles para rol SOPORTE
export const ALL_MODULES = [
  'dashboard',
  'empresas',
  'sucursales',
  'usuarios',
  'configuracion',
  'bancos',
  'movimientos',
  'transferencias',
  'reportes',
  'tesoreria',
  'conciliacion',
  'pos',
  'pos_sin_inventario',
  'configuracion_pos',
  'corte_caja_lite',
  'apariencia_logo_only',
  'integraciones',
  'rh',
  'sat_cfdi',
  'white_label',
  'proveedores',
  'compras',
  'costos',
  'ocr',
  'audit',
];
